### ISSUE TITLE
no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by sasagr** [hotio/overseerr#1]
I tried to update it after some time and I got this error.

pi@raspberrypi:~/overseerr $ docker-compose pull
Pulling overseerr ... pulling from hotio/overseerr                                                                      
ERROR: for overseerr  no matching manifest for linux/arm/v7 in the manifest list entries
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by mrhotio** [comment]
Wait until the next release and arm images are back or use nightly
