### ISSUE TITLE
Overseerr crashes when download sync job runs and hostname of sonarr/radarr cannot be resolved

### ISSUE THREAD

**Issue by clintkev251** [hotio/overseerr#6]
I initially opened[ this issue](https://github.com/sct/overseerr/issues/2356#issue-1086183239) on the main overseerr repo, however in our investigation on that side, we found that the official image did produce an error in this same situation, but did not crash. I'll include the full details of that issue below:

### Description

I've noticed over the last few weeks that overseerr has been periodically crashing. On further investigation this seems to happen when it tries to attempt the download sync job when any of the radarr or sonarr instances are not available. This occurs for me when either of these applications are being updated, and as such are temporarily unavailable. Overseerr doesn't seem to know how to handle this exception

### Version

1.27.0

### Steps to Reproduce

1. Stop sonarr/radarr
2. Run update job
3. Overseerr crashes

### Logs

```shell
2021-12-21T19:47:45.411Z [debug][Jobs]: Starting scheduled job: Download Sync 
/app/dist/api/servarr/base.js:48
                throw new Error(`[${this.apiName}] Failed to retrieve queue: ${e.message}`);
                      ^

 PMError: [Sonarr] Failed to retrieve queue: getaddrinfo ENOTFOUND sonarr
    at SonarrAPI.ServarrBase.getQueue (/app/dist/api/servarr/base.js:48:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/dist/lib/downloadtracker.js:96:36
    at async Promise.all (index 0)
 PMerror Command failed with exit code 1.
```

### Platform

desktop

### Device

N/A

### Operating System

Unraid 6.9 (docker)

### Browser

N/A

### Code of Conduct

- [x] I agree to follow Overseerr's Code of Conduct

**Comment by mrhotio** [comment]
I'll try and reproduce this....ping me if I forget....

**Comment by mrhotio** [comment]
Reproduced it, found the problem, consider it a overseerr issue.

**Comment by TheCatLady** [comment]
sct/overseerr#2358
